"""empty message

Revision ID: 781a4c0aec88
Revises: 5eeeed9fecf6
Create Date: 2023-07-06 17:20:30.327178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781a4c0aec88'
down_revision = '5eeeed9fecf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
